# Site settings
title: Philip Adzanoukpe's Blog
email: epigos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Philip Adzanoukpe's programming blog on python, php, javascripts, datascience programming.
keywords: >
  Philip Adzanoukpe, programming, blog, python, php, datascience, javascripts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://epigos.me" # the base hostname & protocol for your site
twitter_username: epigos
github_username:  epigos

- permalink: pretty

# Build settings
markdown: kramdown

author:
  twitter: epigos

author: epigos

social:
  name: Philip Adzanoukpe
  links:
    - https://twitter.com/epigos
    - https://www.facebook.com/adzanoukpe.philip
    - https://gh.linkedin.com/in/philipadzanoukpe
    - https://plus.google.com/u/1/+PhilipAdzanoukpe2

gems:
  - jekyll-seo-tag
